{% set name = "sphinx-proof" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-proof-{{ version }}.tar.gz
  sha256: 12e7deb3feb3e16b9d59f7c3db8bb16cf6d465bc209aa6b99924d1000f9b9ce9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - docutils >=0.15
    - sphinx
    - sphinx-book-theme

test:
  imports:
    - sphinx_proof
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/executablebooks/sphinx-proof
  summary: A Sphinx extension for producing proofs, theorems, axioms, etc.
  dev_url: https://github.com/executablebooks/sphinx-proof
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agoose77
