{% set name = "sphinx-proof" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d40008fde3c9d96f2ab5b7b54828a86348cb3ec05480ea54b056cf4851a009c0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - docutils >=0.15
    - sphinx
    - sphinx-book-theme

test:
  imports:
    - sphinx_proof
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/executablebooks/sphinx-proof
  summary: A Sphinx extension for producing proofs, theorems, axioms, etc.
  dev_url: https://github.com/executablebooks/sphinx-proof
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agoose77
